
"""Semantic lint: catches the mistakes that make models look broken."""
import numpy as np

from . import checks as wchecks


def _crossings(points, A, B, C):
    """How many of triangles ABC each point's +X ray crosses (Möller–Trumbore)."""
    e1, e2 = B - A, C - A
    d = np.array([1.0, 0.0, 0.0])
    h = np.cross(d, e2)
    det = np.einsum("ij,ij->i", e1, h)
    live = np.abs(det) > 1e-12
    if not live.any():
        return np.zeros(len(points), dtype=int)
    e1, e2, A2, h, det = e1[live], e2[live], A[live], h[live], det[live]
    inv = 1.0 / det
    out = np.zeros(len(points), dtype=int)
    for pi, p in enumerate(points):
        s = p - A2
        u = inv * np.einsum("ij,ij->i", s, h)
        q = np.cross(s, e1)
        v = inv * q[:, 0]                          # d · q with d = +X
        t = inv * np.einsum("ij,ij->i", e2, q)
        hit = (u >= 0) & (u <= 1) & (v >= 0) & (u + v <= 1) & (t > 1e-9)
        out[pi] = int(hit.sum())
    return out


def _buried_parts(V, T, ranges, samples=24):
    """Parts whose geometry lies entirely inside another part.

    `on=` exists precisely so attachments sit on a surface, and an emblem or
    a spike that sank inside its host compiles perfectly cleanly — nothing
    else in the lint can see it. Containment is tested against one part at a
    time, so something hidden by the *union* of several parts still slips
    through.
    """
    found = []
    if not len(T):
        return found
    boxes = {}
    for name, (v0, v1) in ranges.items():
        if v1 - v0 >= 4:
            boxes[name] = (V[v0:v1].min(axis=0), V[v0:v1].max(axis=0))
    tri_owner = {}
    for name, (v0, v1) in ranges.items():
        sel = (T[:, 0] >= v0) & (T[:, 0] < v1)
        if sel.any():
            tri_owner[name] = T[sel]
    for a, (alo, ahi) in boxes.items():
        for b, (blo, bhi) in boxes.items():
            if a == b or b not in tri_owner:
                continue
            if not (np.all(alo >= blo - 1e-9) and np.all(ahi <= bhi + 1e-9)):
                continue                      # bbox not contained: cheap out
            v0, v1 = ranges[a]
            pts = V[v0:v1]
            if len(pts) > samples:
                pts = pts[:: len(pts) // samples]
            tb = tri_owner[b]
            n = _crossings(pts, V[tb[:, 0]], V[tb[:, 1]], V[tb[:, 2]])
            if (n % 2 == 1).mean() > 0.95:    # odd crossings = inside
                found.append((a, b))
                break
    return found


def lint(model, bones, mesh):
    warnings = list(getattr(mesh, "warnings", []))
    infos = []
    V, T, M = mesh.arrays()
    if len(V) == 0:
        return ["model produced no geometry"], infos

    height = V[:, 1].max() - min(V[:, 1].min(), 0)

    # 1. bones with no geometry nearby
    covered = set()
    for sk in mesh.skin:
        for bn, w in sk:
            if w > 0.05:
                covered.add(bn)
    for name, b in bones.items():
        if b.len > 0.01 and name not in covered:
            mid = (b.head + b.tail) / 2
            d = np.linalg.norm(V - mid, axis=1).min()
            if d > 0.06:
                warnings.append("bone %r has no geometry attached or near it "
                                "(nearest vertex %.2f away)" % (name, d))

    # 2. feet below / above ground
    ymin = V[:, 1].min()
    if ymin < -0.02:
        warnings.append("geometry dips %.3f below the ground plane (y=0) — "
                        "legs too long or root too low" % -ymin)
    elif ymin > 0.02:
        warnings.append("lowest geometry floats %.3f above ground (y=0) — "
                        "legs too short or root too high" % ymin)

    # 3. symmetry, per part rather than per silhouette.
    #
    # Comparing the whole model's left and right extents is unusable the
    # moment a character carries a sword in one hand and a shield on the
    # other: nothing but a bare figure can pass, and tuning a prop's spin
    # against a crossguard's length to silence it is worse than the warning.
    # Only a part that straddles the centerline is claiming to be symmetric —
    # a one-sided part and a rigid `group` prop are the author's business.
    in_group = {p["name"] for p in model.parts if p.get("group")}
    for pname, (v0, v1) in mesh.part_ranges.items():
        if v1 - v0 < 4 or pname.rsplit(".", 1)[0] in in_group:
            continue
        if pname.endswith((".l", ".r")):
            continue                      # generated by reflection; exact
        chunk = V[v0:v1]
        xlo, xhi = chunk[:, 0].min(), chunk[:, 0].max()
        if xlo > -0.01 or xhi < 0.01:
            continue                      # sits to one side: intentional
        off = abs(xhi + xlo)
        if off > 0.02:
            warnings.append(
                "part %r straddles the centerline but is lopsided (extends "
                "%.3f left, %.3f right) — a central part should be symmetric; "
                "check its ring `side=` offsets, or move it fully to one side"
                % (pname, xhi, -xlo))

    # 4. proportions report
    total_h = V[:, 1].max() - ymin
    span = V[:, 0].max() - V[:, 0].min()
    depth = V[:, 2].max() - V[:, 2].min()
    infos.append("bbox: height %.2f, width %.2f, depth %.2f (of model height)"
                 % (total_h, span, depth))
    head_parts = [k for k in mesh.part_ranges if "head" in k]
    if head_parts:
        v0, v1 = mesh.part_ranges[head_parts[0]]
        hh = V[v0:v1, 1].max() - V[v0:v1, 1].min()
        if hh > 1e-6:
            infos.append("figure is %.1f head-heights tall" % (total_h / hh))

    # 5. part origin closer to another bone than its host: wrong-binding smell
    def seg_dist(p, bone):
        a0, d, L = bone.head, bone.dir, bone.len
        t = float(np.clip(np.dot(p - a0, d), 0, max(L, 1e-9)))
        return float(np.linalg.norm(p - (a0 + d * t)))

    for part in model.parts:
        if "bone" not in part:
            continue
        host_ref = part["bone"]
        hb = bones.get(host_ref) or bones.get(host_ref + ".l")
        if hb is None:
            continue
        origin = hb.point_at(part.get("at", 1.0)) + np.array(part.get("offset", (0, 0, 0)))
        d_host = seg_dist(origin, hb)
        best_name, d_best = None, 1e9
        for name, ob in bones.items():
            if ob.len < 1e-6:
                continue
            dd = seg_dist(origin, ob)
            if dd < d_best:
                best_name, d_best = name, dd
        if (best_name and bones[best_name] is not hb
                and d_host > 0.08 and d_host > 1.6 * d_best):
            warnings.append(
                "part %r is hosted on %r but its origin sits nearer to %r "
                "(%.3f vs %.3f) — it will be rigidly skinned to %r; host it on "
                "the bone it visually attaches to"
                % (part["name"], host_ref, best_name, d_best, d_host, host_ref))

    # 6. degenerate triangles
    if len(T):
        a, b, c = V[T[:, 0]], V[T[:, 1]], V[T[:, 2]]
        areas = np.linalg.norm(np.cross(b - a, c - a), axis=1) / 2
        ndeg = int((areas < 1e-10).sum())
        if ndeg:
            warnings.append("%d degenerate (zero-area) triangles — every "
                            "generator emits fans and strips that collapse "
                            "cleanly, so this means overlapping ring centers "
                            "or a zero-length path segment" % ndeg)

        # Shared manifold edges must be traversed in opposite directions by
        # their two incident triangles. Same-direction pairs are a precise
        # indicator of inconsistent winding and become holes under Godot's
        # default backface culling.
        edges = {}
        for ti, tri in enumerate(T):
            for u, v in ((int(tri[0]), int(tri[1])),
                         (int(tri[1]), int(tri[2])),
                         (int(tri[2]), int(tri[0]))):
                if u == v:
                    continue
                key = (u, v) if u < v else (v, u)
                direction = 1 if (u, v) == key else -1
                edges.setdefault(key, []).append((ti, direction))
        inconsistent = sum(1 for uses in edges.values()
                           if len(uses) == 2 and uses[0][1] == uses[1][1])
        nonmanifold = sum(1 for uses in edges.values() if len(uses) > 2)
        if inconsistent:
            warnings.append("%d shared edges have inconsistent triangle winding"
                            % inconsistent)
        if nonmanifold:
            warnings.append("%d non-manifold edges are used by more than two triangles"
                            % nonmanifold)

    # 6b. parts swallowed whole by another part
    for a, b in _buried_parts(V, T, mesh.part_ranges):
        warnings.append(
            "part %r is entirely inside %r — it is invisible from every "
            "angle, so it costs triangles and shows nothing; move it out, "
            "grow it past the surface, or place it with on=%s"
            % (a, b, b.rsplit(".", 1)[0]))

    double_sided = sorted(getattr(mesh, "double_sided_materials", ()))
    if double_sided:
        infos.append("double-sided materials: %s" % ", ".join(double_sided))

    # 7. authored measurement checks
    fails, measurements = wchecks.evaluate(model, bones, mesh, V)
    warnings.extend("check failed — %s" % f for f in fails)
    infos.extend("check: %s" % m for m in measurements)

    infos.append("%d vertices, %d triangles, %d materials"
                 % (len(V), len(T), len(mesh.materials)))
    return warnings, infos
